language: c
dist: trusty
sudo: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/texlive-2017'
    packages:
    - texlive-full
    - biber
    - fonts-ebgaramond

install:
 - make

script:
  -
